name: Deploy to Firebase Hosting and Functions

on:
  push:
    branches:
      - main
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 1. Functions की डिपेंडेंसी इंस्टॉल करें
      - name: Install Functions Dependencies
        run: |
          cd functions
          npm ci

      # 2. Hosting और Functions दोनों को आधिकारिक फ़ायरबेस एक्शन से डिप्लॉय करें
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: push-notifaction-c3460
