name: Deploy to Firebase Hosting and Functions

on:
  push:
    branches:
      - main
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 1. Functions की डिपेंडेंसी इंस्टॉल करें
      - name: Install Functions Dependencies
        run: |
          cd functions
          npm install

      # 2. Firebase CLI इंस्टॉल करें
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 3. Service Account से ऑथेंटिकेट करके डिप्लॉय करें
      - name: Deploy to Firebase
        env:
          GCP_SA_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        run: |
          echo "$GCP_SA_KEY" > key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/key.json"
          firebase deploy --only functions,hosting --project push-notifaction-c3460 --non-interactive
          rm key.json
